[character]
success_symbol = "[ï€Œ](bold green)"
error_symbol = "[ï€](bold red)"
format = "$symbol [î˜‚](bold white) "

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
read_only = "ï‘ˆï ½"
style = "bold"
format = "[$path]($style) [$read_only]($read_only_style)($style)"

[cmd_duration]
min_time = 2_000
format = "task completed in [$duration](bold yellow)"

[git_status]
conflicted = "ï²…"
ahead = "ï°²"
behind = "ï°¯"
diverged = "ï•šï•›"
up_to_date = "âœ“"
untracked = "ï¦±"
stashed = "ï…¬"
modified = "ï‘™"
staged = 'ï±'
renamed = "ï€«"
deleted = "ï‡¸"

[package]
format = "via [ğŸ $version](208 bold) "

[time]
disabled = false
format = '[î‰]($style) [$time]($style) [ïœ¹]($style) '
style = "Bold Blue"
time_format = "%T"
utc_time_offset = "3"
time_range = "00:00:00-24:00:00"
